#Spring Boot Application Name
environment.name=dev

#Spring DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/flowtrack
spring.datasource.username=postgres
spring.datasource.password=fabs
spring.datasource.driver-class-name=org.postgresql.Driver

#Spring Boot JPA Configuration
spring.jpa.show-sql=true


