#Spring Boot Application Name
environment.name=dev

#Spring DataSource Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:flowtrack}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:fabs}
spring.datasource.driver-class-name=org.postgresql.Driver

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:c4odsogu}
cloudinary.api-key=${CLOUDINARY_API_KEY:658879758158299}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:OQqdRA0PTinbLioVrkOBHSxMFJs}
cloudinary.folder=${CLOUDINARY_FOLDER:flowtrack/inventario-yolo}

#Spring Boot JPA Configuration
spring.jpa.show-sql=true